// Master TOC generator for the global Obsidian vault.
//
// Builds `.od/obsidian-global/README.md` from the current note set.
// Acts as the "front door" for any chat session — both the in-app
// chat agent and external MCP consumers can Read this ONE file and
// see the complete project landscape (categories + every note's
// title + brief). Without it the agent has to Glob/Grep per turn,
// which burns tools-calls.
//
// Regeneration triggers:
//   • Every successful indexer file write (cheap; coalesced).
//   • Every manual UI save via writeNote.
//   • Tier completion in the indexer.

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { listAllNotes, vaultRoot } from './storage.js';

const TOC_FILENAME = 'README.md';
const TOC_MARKER = '<!-- auto-generated by obsidian indexer; edits will be overwritten -->';

let pendingRebuild: Promise<void> | null = null;
let coalesceTimer: ReturnType<typeof setTimeout> | null = null;

// Debounce frequent calls (e.g. every per-file note write during an
// indexer run) into one rebuild per 500ms. Final read-modify-write
// over the master README is still atomic.
export function scheduleTocRebuild(): void {
  if (coalesceTimer) clearTimeout(coalesceTimer);
  coalesceTimer = setTimeout(() => {
    coalesceTimer = null;
    if (pendingRebuild) return;
    pendingRebuild = rebuildToc().finally(() => { pendingRebuild = null; });
  }, 500);
}

// Force-flush any pending debounced rebuild and wait for it. Called at
// tier boundaries / indexer-finish so the master TOC is durable on disk
// before we move on, instead of sitting in the 500ms debounce window
// where a daemon crash would leave the TOC stale.
export async function flushTocRebuild(): Promise<void> {
  if (coalesceTimer) {
    clearTimeout(coalesceTimer);
    coalesceTimer = null;
  }
  if (pendingRebuild) {
    await pendingRebuild;
  }
  pendingRebuild = rebuildToc().finally(() => { pendingRebuild = null; });
  await pendingRebuild;
}

export async function rebuildToc(): Promise<void> {
  const notes = await listAllNotes();
  // Skip the TOC itself so we never recurse into our own list.
  const noteEntries = notes
    .filter((n) => n.path !== 'README' && !n.path.startsWith('.'))
    .map((n) => ({
      path: n.path,
      title: n.title,
      category: categoryFromPath(n.path),
      brief: firstNonHeadingLine(n.content),
      tier: tierFromContent(n.content),
    }));

  // Group by category, sort categories alphabetically, notes
  // alphabetically within. Root-level notes go under "Корінь".
  const byCategory = new Map<string, typeof noteEntries>();
  for (const entry of noteEntries) {
    const arr = byCategory.get(entry.category) ?? [];
    arr.push(entry);
    byCategory.set(entry.category, arr);
  }

  const lines: string[] = [];
  lines.push('# Open Design — База знань');
  lines.push('');
  lines.push(TOC_MARKER);
  lines.push('');
  lines.push(`Згенеровано: ${new Date().toISOString()}`);
  lines.push(`Всього нотаток: **${noteEntries.length}** у **${byCategory.size}** категоріях.`);
  lines.push('');
  lines.push('Це автозгенерований індекс. Кожен запит у чаті починається з Read цього файла, тож агент знає що в базі є БЕЗ окремого Glob/Grep.');
  lines.push('');

  const sortedCategories = Array.from(byCategory.keys()).sort((a, b) => a.localeCompare(b, 'uk'));
  for (const category of sortedCategories) {
    const entries = (byCategory.get(category) ?? []).slice().sort((a, b) => a.title.localeCompare(b.title, 'uk'));
    lines.push(`## ${category} (${entries.length})`);
    lines.push('');
    for (const e of entries) {
      const tierBadge = e.tier ? ` _T${e.tier}_` : '';
      lines.push(`- [[${e.path}|${e.title}]]${tierBadge}${e.brief ? ` — ${e.brief}` : ''}`);
    }
    lines.push('');
  }

  await mkdir(vaultRoot(), { recursive: true });
  await writeFile(path.join(vaultRoot(), TOC_FILENAME), lines.join('\n'), 'utf-8');
}

function categoryFromPath(notePath: string): string {
  if (!notePath.includes('/')) return 'Корінь';
  const head = notePath.split('/')[0];
  return head ?? 'Корінь';
}

function firstNonHeadingLine(content: string): string {
  const lines = content.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) continue;
    if (line.startsWith('<!--')) continue;
    // Strip simple markdown emphasis so the TOC blurb reads cleanly.
    const cleaned = line.replace(/[*_`]/g, '').slice(0, 120);
    return cleaned.length === line.length ? cleaned : cleaned + '…';
  }
  return '';
}

function tierFromContent(content: string): number | null {
  const match = content.match(/<!--\s*tier:\s*(\d)\s*-->/);
  if (!match) return null;
  const n = Number(match[1]);
  return Number.isFinite(n) ? n : null;
}
